import Image from "next/image";
import Head from "next/head";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import Box from "@mui/material/Box";

import { Typography } from "@mui/material";
import Link from "next/link";

export default function Home({ productList }) {
  console.log(productList);
  return (
    <>
      <Head>
        <title>Dr Saina test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="sm">
        <Grid container>
          {productList &&
            productList.map(({ id, image, title, price }) => (
              <Grid item xs={6} sm={6} key={id}>
                <Link href={`/product/${encodeURIComponent(id)}`}>
                  <img
                    src={image}
                    style={{ objectFit: "contain" }}
                    width={"100%"}
                    alt={title}
                  />
                  {/* <Image
                    src={image}
                    fill
                    style={{ objectFit: "contain" }}
                    // width={100} height={500}

                    alt={title}
                  /> */}
                  <Stack justifyContent="space-between">
                    <Box>
                      <Typography>{title}</Typography>
                    </Box>
                    <Box>
                      <Typography>${price}</Typography>
                    </Box>
                  </Stack>
                </Link>
              </Grid>
            ))}
        </Grid>
      </Container>
    </>
  );
}

export const getServerSideProps = async () => {
  const productListRes = await fetch("https://fakestoreapi.com/products");
  const productList = await productListRes.json();
  return {
    props: {
      productList,
    },
  };
};
